### ISSUE TITLE
SNP format input for RClone 

### ISSUE THREAD

**Issue by mstagliamonte** [dbailleul/RClone#1]
Hi, Thank you for RClone!

I was reading the manual, and I would like some more detail regarding the input formatting in case of SNP data. is it the same as microsatellite, just replacing the repeat number with the nucleotide allele?

Kind Regards,
Max

**Comment by dbailleul** [comment]
Hi Max, thanks for using RClone !
I'm not really sure to understand your question ... is it related to genetic distance ?

**Comment by mstagliamonte** [comment]
Hi, DBailleul,

I was trying to use RClone with SNP data, i.e. genotypes would have nucleotides rather then repeat lengths (e.g. A/A, G/C, etc...). I was wondering how to format my input. Can I just use characters? Something like this:
Two samples, two loci: Sample1: (A/A, C/G)  Sample2: (A/T, G/G) would become:
```
                      Locus 1_1      Locus1_2          Locus2_1        Locus2_2
Sample1                A                  A                 C             G
Sample2                A                  T                 G             G
```

Is that correct? Or is RClone better suited to analyze microsatellite data only?

Thank you for your kind attention,
Max

**Comment by dbailleul** [comment]
Theorically, you should be able to use letters (A/T/C/G) instead of numbers (101/000) with RClone.
But just to be sure, I would advise to change A = 101, T = 102, C = 103 and G = 104 "just in case".

RClone is suitable to handle SNP data.
The only problem is that I've never finished to implement missing data as _true_ missing data (ie not another allele as "000" would be considered now).
You know how postdoc are ... but I hope I will be able one day.

**Comment by mstagliamonte** [comment]
Yeah, I know ;-)

Thank you for your help, and good luck.
Max
